- netx/net/sourceforge/jnlp/cache/CacheEntry.java
- netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
- tests/netx/unit/net/sourceforge/jnlp/cache/CacheEntryTest.java
see: https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=1777
> IcedTea-Web always redownloads web start application if they are packed

- README.md
first simple readme added. See #24
> first simple readme added

- README.md
> label highlighting in readme

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- JAVA_STYLE_GUIDE.md
> code of conduction & styleguide

- common/pom.xml
- core/pom.xml
- core/src/main/java/net/sourceforge/jnlp/AppletDesc.java
- core/src/main/java/net/sourceforge/jnlp/ExtensionDesc.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/Launcher.java
- core/src/main/java/net/sourceforge/jnlp/MalformedXMLParser.java
- core/src/main/java/net/sourceforge/jnlp/NetxPanel.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
- core/src/main/java/net/sourceforge/jnlp/Version.java
- core/src/main/java/net/sourceforge/jnlp/browser/BrowserAwareProxySelector.java
- core/src/main/java/net/sourceforge/jnlp/browser/FirefoxPreferencesFinder.java
- core/src/main/java/net/sourceforge/jnlp/browser/FirefoxPreferencesParser.java
- core/src/main/java/net/sourceforge/jnlp/cache/CacheEntry.java
- core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
- core/src/main/java/net/sourceforge/jnlp/cache/NativeLibraryStorage.java
- core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
- core/src/main/java/net/sourceforge/jnlp/cache/ResourceTracker.java
- core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
- core/src/main/java/net/sourceforge/jnlp/controlpanel/JVMPanel.java
- core/src/main/java/net/sourceforge/jnlp/jdk89acesses/JarIndexAccess.java
- core/src/main/java/net/sourceforge/jnlp/runtime/ApplicationInstance.java
- core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
- core/src/main/java/net/sourceforge/jnlp/runtime/HtmlBoot.java
- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
- core/src/main/java/net/sourceforge/jnlp/runtime/JnlpBoot.java
- core/src/test/java/net/sourceforge/jnlp/runtime/CodeBaseClassLoaderTest.java
SLF4J API introduced
core uses SLF4J simple for now
SLF4J logger used in several classes
> SLF4J introduced

- common/src/main/java/net/sourceforge/jnlp/runtime/Translator.java
- core/src/main/java/net/sourceforge/jnlp/config/BasicValueValidators.java
- core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
- core/src/main/java/net/sourceforge/jnlp/services/XBasicService.java
moved static config part closer to config package for now. Not perfect but breaks the dependency of Translator to DeploymentConfiguration
> move Translator to common module

- core/src/main/java/net/sourceforge/jnlp/util/BasicExceptionDialog.java
- core/src/main/java/net/sourceforge/jnlp/util/GenericDesktopEntry.java
- core/src/main/java/net/sourceforge/jnlp/util/InvalidJarHeaderException.java
- core/src/main/java/net/sourceforge/jnlp/util/MD5SumWatcher.java
- core/src/main/java/net/sourceforge/jnlp/util/PropertiesFile.java
- core/src/main/java/net/sourceforge/jnlp/util/StreamUtils.java
- core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java
some changes based on java style guide
> some changes based on java style guide

- core/src/main/java/net/sourceforge/jnlp/security/CertificateUtils.java
- core/src/main/java/net/sourceforge/jnlp/security/VariableX509TrustManager.java
Some refactoring of security classes / functionality-
> Security refactoring

- LICENCE_DETAILS.md
- README.md
> more content in readme

- core/src/test/resources/simplelogger.properties
> config file for slf4j-simple

- core/src/main/java/net/sourceforge/jnlp/util/logging/FileLog.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/LogConfig.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/OutputController.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/SingleStreamLogger.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/TeeOutputStream.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/filelogs/WriterBasedFileLog.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/headers/Header.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/headers/JavaMessage.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/headers/ObservableMessagesProvider.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/headers/PluginMessage.java
refactoring of logging package based on IntelliJ Analyzer
> refactoring of logging package based on IntelliJ Analyzer

- core/src/main/java/net/sourceforge/jnlp/util/docprovider/IcedTeaWebTextsProvider.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/ItwebSettingsTextsProvider.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/TextsProvider.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/Formatter.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/HtmlFormatter.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/ManFormatter.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/PlainTextFormatter.java
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/ReplacingTextFormatter.java
- core/src/test/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/ReplacingTextFormatterTest.java
refactoring of docprovider package based on IntelliJ Analyzer
> refactoring of docprovider package based on IntelliJ Analyzer

- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/main/java/net/sourceforge/jnlp/util/LocaleUtils.java
- core/src/test/java/net/sourceforge/jnlp/JNLPFileTest.java
- core/src/test/java/net/sourceforge/jnlp/util/LocaleUtilsTest.java
isolate pure locale handling functionality into LocaleUtils class to simplify Parser and JNLPFile
> isolate pure locale handling functionality into LocaleUtils

- common/src/main/java/net/adoptopenjdk/icedteaweb/jvm/JVMUtils.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
isolated pure JVM argument checking functionality into JVMUtils class to simplify Parser
> isolated pure JVM argument checking functionality into JVMUtils

- core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
- core/src/test/java/net/sourceforge/jnlp/cache/ResourceDownloaderTest.java
make UrlRequestResult unmodifiable and some code formatting
> Refactor resource downloader

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyFileModel.java
> Read/Write the policy files with the UTF-8 encoding

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationType.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/extension/ComponentDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/extension/InstallerDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- Refactored component desc element
- Refactored installer desc element
- some const extraction
- improved javadoc and make reference to JSR
> Refactored component/installer desc elements

- jnlp-servlet/LICENSE.txt
- jnlp-servlet/README.md
- jnlp-servlet/pom.xml
- jnlp-servlet/src/main/java/jnlp/sample/jardiff/JarDiff.java
- jnlp-servlet/src/main/java/jnlp/sample/jardiff/JarDiffConstants.java
- jnlp-servlet/src/main/java/jnlp/sample/jardiff/JarDiffPatcher.java
- jnlp-servlet/src/main/java/jnlp/sample/jardiff/Patcher.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/DownloadRequest.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/DownloadResponse.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/ErrorResponseException.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/JarDiffHandler.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/JnlpDownloadServlet.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/JnlpFileHandler.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/JnlpFileHandlerHook.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/JnlpResource.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/Logger.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/ResourceCatalog.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/XMLAttribute.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/XMLNode.java
- jnlp-servlet/src/main/java/jnlp/sample/servlet/XMLParsing.java
- jnlp-servlet/src/main/java/jnlp/sample/util/VersionID.java
- jnlp-servlet/src/main/java/jnlp/sample/util/VersionString.java
- jnlp-servlet/src/main/resources/jnlp/sample/jardiff/resources/strings.properties
- jnlp-servlet/src/main/resources/jnlp/sample/servlet/resources/strings.properties
- pom.xml
Module taken as copy from https://github.com/mojohaus/webstart
> JNLP servlet module added

- clients/pom.xml
- common/pom.xml
- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages.properties
- core/pom.xml
- core/src/main/java/net/sourceforge/jnlp/util/docprovider/TextsProvider.java
- core/src/test/java/net/sourceforge/jnlp/util/docprovider/ReadAuthorsTest.java
- integration/pom.xml
- jnlp-api/pom.xml
- jnlp-servlet/pom.xml
- launchers/build.sh
- launchers/configure.sh
- launchers/pom.xml
- launchers/utils.sh
- pom.xml
- test-extensions/pom.xml
- xml-parser/pom.xml
Added generation of docs in new environment; docs aligned with current state
* As version is now exposed, bumped to 2.0
* Doccumented death of plugin
* no longer processing authors file
* adapted test to it and formatter usage
* docs propagated to images; windows get removed man o
> Generated docs

- core/src/main/java/net/sourceforge/jnlp/util/logging/BasicOutputController.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/OutputController.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/TeeOutputStream.java
- core/src/test/java/net/sourceforge/jnlp/util/logging/TeeOutputStreamTest.java
- convert from Whitebox to Blackboxtest
- resolved Windows issues in test
> Cleanup TeeOutputStreamTest

- netx/net/sourceforge/jnlp/cache/CacheUtil.java
- tests/netx/unit/net/sourceforge/jnlp/PluginBridgeTest.java
> backport deadlock fix from #219

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ResourcesDesc.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- extracted some more element and attribute constants while studying the code
> extracted some more element and attribute constants

- core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
- core/src/test/java/net/sourceforge/jnlp/config/DeploymentConfigurationTest.java
- fix erroneously removal of .locked entries in deployment.properties file
- improved NPE-prone property loading
- improved exception handling
- refined logging and documentation
> fix erroneously removal of .locked entries in deployment.properties

- core/pom.xml
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/commandline/CommandLine.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyEditor.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/commandline/HelpCommandTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/ErrorSplashUtilsTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/SplashUtilsTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyEditorTest.java
- core/src/test/java/net/sourceforge/jnlp/cache/CacheLRUWrapperTest.java
- core/src/test/java/net/sourceforge/jnlp/config/DirectoryValidatorTest.java
- core/src/test/java/net/sourceforge/jnlp/util/logging/TeeOutputStreamTest.java
- test-extensions/src/main/java/net/adoptopenjdk/icedteaweb/testing/AnnotationConditionChecker.java
This PR fixes the remaining issues we have when running the test on windows
> Fix tests on windows

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/DownloadStrategy.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ExtensionDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JARDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- extracted download strategy values as enum
- extracted download element names and attributes as consts
> Refactoring download attribute

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ExtensionDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JARDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- some more refactoring extracting element and attribute consts
> Refactored resources desc

- pom.xml
- enabled adding implementation and specification entries into manifest to see build version
- extracted plugin versions as properties
> enabled adding implementation and specification entries into manifest

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/PackageDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- extracted consts
- improved javadoc
> minor package descriptor refactoring

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/ShortcutDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JARDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/PropertyDesc.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/test/java/net/sourceforge/jnlp/ParserTest.java
- match jnlp element attributes and sub elements in descriptor classes with spec
- add TODOs for the missing ones
> Match elements and attributes in Desc with spec

- netx/net/sourceforge/jnlp/runtime/JNLPPolicy.java
> Forced recognition of system jars (1.8)

- netx/net/sourceforge/jnlp/runtime/ManifestAttributesChecker.java
- netx/net/sourceforge/jnlp/util/UrlUtils.java
- tests/netx/unit/net/sourceforge/jnlp/util/UrlUtilsTest.java
> fix(ManifestAttributesChecker): jars must be relative to codebase

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
Should be fixing the https://github.com/AdoptOpenJDK/IcedTea-Web/issues/217
> If streams are disabled, and console enabled, silent also client application

- common/src/main/java/net/adoptopenjdk/icedteaweb/logging/BaseLogger.java
- common/src/test/java/net/adoptopenjdk/icedteaweb/logging/BaseLoggerTest.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/OutputControllerLoggerFactory.java
- core/src/test/java/net/sourceforge/jnlp/util/logging/OutputControllerLoggerTest.java
- fix bug in message expanding
- add more tests
> Base logger message expand fix

- netx/net/sourceforge/jnlp/runtime/JNLPPolicy.java
- tests/netx/unit/net/sourceforge/jnlp/runtime/JNLPPolicyTest.java
> support handling of white space in PolicyURI when on file system

- launchers/rust-launcher/src/os_access.rs
- launchers/rust-launcher/src/utils.rs
> Fix hang in windows when javaws is launched outside the console.

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/appletextendedsecurity/UnsignedAppletTrustConfirmation.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesChecker.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesCheckerTest.java
- core/src/test/java/net/sourceforge/jnlp/JNLPFileTest.java
- core/src/test/resources/net/sourceforge/jnlp/minimal.jnlp
- core/src/test/resources/net/sourceforge/jnlp/minimalWithHref.jnlp
> fix(JNLPFile): location/sourceLocation confusion

- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPProxySelector.java
- core/src/main/java/net/sourceforge/jnlp/runtime/PacEvaluatorFactory.java
- core/src/main/java/net/sourceforge/jnlp/runtime/RhinoBasedPacEvaluator.java
- core/src/main/resources/net/sourceforge/jnlp/build.properties
this PR provides a fix for #303 by adding a build.properties that includes a proper rhino.available setting
> Rhino availability fix

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/extension/InstallerDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/test/java/net/sourceforge/jnlp/ParserTest.java
implement parsing for progress-class attributes of AppletDesc, ApplicationDesc and InstallerDesc
fixes #311
> implement parsing for progress-class attributes

- ChangeLog
- NEWS
- configure.ac
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>
> Release 1.8.2

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/AssociationDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDescTest.java
- core/src/test/java/net/sourceforge/jnlp/JnlpInformationElementTest.java
- core/src/test/java/net/sourceforge/jnlp/ParserBasicTest.java
- core/src/test/resources/net/sourceforge/jnlp/basic.jnlp
according to JSR-56, Section 3.5
> Add parsing of association sub elements icon and description

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/downloadindicator/DefaultDownloadIndicator.java
to be able to display alternative download progress to the user as specified in JSR-56, section 3.5
> implement usage of progress-class attribute in entry point descriptors

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/downloadindicator/DefaultDownloadIndicator.java
JNLPRuntime.getApplication() may lead to NPE, needs further investigation
> revert usage of progress-class attribute impl as does not work correctly

- launchers/build.sh
- launchers/configure.sh
- launchers/utils.sh
fix for build on windows
remove unnecessary hyphen at the end of tail (breaks build on freebsd)
> unbreak build of launchers since merge of PR #266

- common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/SimpleRange.java
- common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionId.java
- common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionIdComparator.java
- common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionRange.java
- common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionString.java
Since #350 was merged before I did a review I put some final changes here in the PR:
- final added
- null checks
- switched 1 method from private -> public since I would like to use it
> review of #350

- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/test/java/net/sourceforge/jnlp/ParserTest.java
- core/src/test/resources/net/sourceforge/jnlp/appletsizes/abs.jnlp
- core/src/test/resources/net/sourceforge/jnlp/appletsizes/bad.jnlp
- core/src/test/resources/net/sourceforge/jnlp/appletsizes/nothing.jnlp
- core/src/test/resources/net/sourceforge/jnlp/appletsizes/percent.jnlp
And thus fixing https://github.com/AdoptOpenJDK/IcedTea-Web/issues/368
> Added support for % character in size of applet-desc

- core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
Fixes #374
btw, I do not know if this is correct fix! Comment from @lherschi would be awesom
> add  pack.gz and .gz conditionally

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/appletextendedsecurity/UnsignedAppletTrustConfirmation.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesChecker.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesCheckerTest.java
- core/src/test/java/net/sourceforge/jnlp/JNLPFileTest.java
> revert PR #294

- core/src/main/java/net/sourceforge/jnlp/Launcher.java
Commits to blame:
https://github.com/AdoptOpenJDK/IcedTea-Web/commit/30f3b04556be5c9289663c8ac6d57539b1fbbc85
https://github.com/AdoptOpenJDK/IcedTea-Web/commit/461969132400174241f825034b6f78065e44ebb6
> Fixed forking issues

- core/src/main/java/net/sourceforge/jnlp/Launcher.java
- core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
- core/src/main/java/net/sourceforge/jnlp/runtime/ForkingStrategy.java
- core/src/main/java/net/sourceforge/jnlp/runtime/HtmlBoot.java
- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPRuntime.java
converting the forksAllow to an enum allows for taking care of all possible states.
Also for the ones of OpenWebStart
> add forkingStrategy

- common/src/main/java/net/adoptopenjdk/icedteaweb/ui/swing/SwingUtils.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanel.java
- center control center on screen
- allow to create instance in OWS
> center control center on screen

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/JNLPSplashScreen.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/SplashUtils.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/impls/DefaultErrorSplashScreen2012.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/impls/DefaultSplashScreen2012.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/ErrorSplashScreenTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/ErrorSplashUtilsTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/SplashScreenTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/SplashUtilsTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/impls/defaultsplashscreen2012/BasePainterTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/impls/defaultsplashscreen2012/ErrorPainterTest.java
> remove width and height from Splashscreen constructors

- core/src/main/java/net/sourceforge/jnlp/cache/CacheDirectory.java
- core/src/main/java/net/sourceforge/jnlp/cache/CacheLRUWrapper.java
- core/src/main/java/net/sourceforge/jnlp/cache/DownloadEvent.java
- core/src/main/java/net/sourceforge/jnlp/cache/DownloadListener.java
- core/src/main/java/net/sourceforge/jnlp/cache/IllegalResourceDescriptorException.java
- core/src/main/java/net/sourceforge/jnlp/cache/NativeLibraryStorage.java
- core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
- core/src/main/java/net/sourceforge/jnlp/cache/ResourceUrlCreator.java
- core/src/test/java/net/sourceforge/jnlp/cache/ResourceDownloaderTest.java
- core/src/test/java/net/sourceforge/jnlp/cache/ResourceUrlCreatorTest.java
some code cleanup and visibility adjustments
> Cache refactoring

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanelStyle.java
after this PR OWS can easily deactivate ITW panels in the Control Center and add new panels.
> decative specific panels in a style

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanel.java
Adds a background color and a top border to the global button panel
> Button panel seperation

- core/src/test/java/net/sourceforge/jnlp/cache/NativeLibraryStorageTest.java
- core/src/test/java/net/sourceforge/jnlp/runtime/JNLPClassLoaderTest.java
- test-extensions/pom.xml
- test-extensions/src/main/java/net/adoptopenjdk/icedteaweb/testing/util/FileTestUtils.java
separating the Java changes from the Travis changes in #451 
Thanks @Artoria2e5 for the valuable contribution
> add @NotThreadSafe as hints to surfier test runner

- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
> only add to codeBaseLoader if codebase is enabled

- core/src/main/java/net/sourceforge/jnlp/cache/CachedDaemonThreadPoolProvider.java
- core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
- core/src/test/java/net/sourceforge/jnlp/cache/ResourceDownloaderTest.java
Some cleanup that is based on the #466 PR.
> Cleanup based on #466

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/apptrustwarningpanel/MatchingALACAttributePanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesChecker.java
Logging added & sample uses valide JNLP
> Logging added & sample uses valide JNLP

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/NetworkSettingsPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/TemporaryInternetFilesPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/util/UiLock.java
- core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
- core/src/main/java/net/sourceforge/jnlp/config/Setting.java
Elements (like textfields or Checkboxes) in the UI can be disabled by a configuration property.
> Functionallity to disable Ui elements

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/ControlPanelProvider.java
By doing so a panel can be added / removed based on the DeploymentConfiguration
> pass config to panel provider active check

- launchers/rust-launcher/src/main.rs
#420 Fix evaluation of -Xnosplash that does not work in pre-release of OpenWebStart 0.4.0.
> #420 Fix evaluation of -Xnosplash

- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/ResourceHandler.java
fixes #497 
fixes https://github.com/karakun/OpenWebStart/issues/69
> use queue of sufficient size

- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages.properties
- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages_de.properties
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/AccessWarningPane.java
- core/src/main/java/net/sourceforge/jnlp/security/AccessType.java
- core/src/main/java/net/sourceforge/jnlp/services/XExtendedService.java
Correct dialog for ExtendedService
> Correct dialog for ExtendedService

- core/src/main/java/net/sourceforge/jnlp/runtime/ApplicationInstance.java
- core/src/main/java/net/sourceforge/jnlp/util/GenericDesktopEntry.java
- core/src/main/java/net/sourceforge/jnlp/util/ShortcutCreationOptions.java
- core/src/main/java/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
- core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
- removed unused sign param
- Enum for shortcuts
> Refactoring for shortcut creation

- launchers/shell-launcher/launchers.bat.in
- launchers/shell-launcher/launchers.sh.in
- launchers/utils.sh
0abc086 was done more as a redo of what I've done in _batch_ in 5403cf1 and since my _bash_ experiences aren't plenty, I was unsure of what to expect from the found entry - can it be a symlink? Should I even check for javac on Linux? Feedback is welcome. Idea from @judovana.
> Launcher catchup 2 - Path iteration

- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/downloader/BaseResourceDownloader.java
fixes https://github.com/karakun/OpenWebStart/issues/102
> set local file if cache is upToDate

- common/src/main/java/net/adoptopenjdk/icedteaweb/jdk89access/SunMiscLauncher.java
> Do not log missing sun.misc.Launcher as error

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/certificateviewer/CertificatePane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
Add a button to view certificates from the java console
> Certificates in console

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
By adding this attribute we can select a JDK from a specific vendor (in OpenWebStart)
> vendor attribute added to jnlp desc

- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/util/GenericDesktopEntry.java
- core/src/main/java/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
- core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
closes https://github.com/karakun/OpenWebStart/issues/136
> unified how the shortcuts (desktop and menu) are named

- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages.properties
As discussed in the issue, this is a number of spelling fixes, most of which are very minor.
I'm happy to discuss if I've misunderstood something.
> Issue 611: Minor typo fixes to english texts

- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages_de.properties
Related to issue 611, I couldn't help noticing some minor typos in the German messages too - please feel free to review / correct.
> Minor typo fixes for German

- RELEASE.md
add how to integrated last ITW into AdopOpenJDK installer
> Update RELEASE.md configure installer release job

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanel.java
Some padding for the settings menu
> Padding for menu

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/AbstractUrlWhitelistPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/ServerWhitelistPanel.java
- core/src/main/java/net/sourceforge/jnlp/util/whitelist/UrlWhiteListUtils.java
These are the same changes as in #687 
Except they are applied to the current master to resolve the conflicts
> JVM whitelist: apply changes from #687 to current master

- core/src/main/java/net/sourceforge/jnlp/cache/NativeLibraryStorage.java
- core/src/main/java/net/sourceforge/jnlp/runtime/classloader/JNLPClassLoader.java
fixes https://github.com/karakun/OpenWebStart/issues/323
> fix native library loading in macOS when using old .jnilib extension

- .travis.yml
- AUTHORS
Added AdoptJDK8 installation in Travis-CI integration.
> Travis integration

- netx/net/sourceforge/jnlp/Launcher.java
- netx/net/sourceforge/jnlp/OptionsDefinitions.java
- netx/net/sourceforge/jnlp/cache/CacheEntry.java
- netx/net/sourceforge/jnlp/cache/CacheUtil.java
- netx/net/sourceforge/jnlp/cache/CachedDaemonThreadPoolProvider.java
- netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
- netx/net/sourceforge/jnlp/cache/ResourceTracker.java
- netx/net/sourceforge/jnlp/config/Defaults.java
- netx/net/sourceforge/jnlp/config/DeploymentConfiguration.java
- netx/net/sourceforge/jnlp/resources/Messages.properties
- netx/net/sourceforge/jnlp/runtime/Boot.java
- netx/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
- netx/net/sourceforge/jnlp/runtime/JNLPRuntime.java
- netx/net/sourceforge/jnlp/tools/JarCertVerifier.java
- netx/net/sourceforge/jnlp/util/PropertiesFile.java
For detailed results see: https://github.com/judovana/GenerateUnlimitedNumberOfJars
Lmited number of visible download bars
Added proeprties for backward compatibility and fortuning above
Originally by akaschen@redhat.com
> Reduced number of threads spawned for downloading of resources. Speedup is aprox 200-300%

- netx/net/sourceforge/nanoxml/XMLElement.java
> handle broken XML in jnlp

- .github/workflows/build.yml
- .github/workflows/windows_build.sh
MAKE SURE TO SQUASH WHEN LANDING (36 commits)
Next Steps:
We need to find a way to sign the zip/msi files. I'll do some investigation to find out the best way to handle this.
> ITW 1.8 add windows build

- .github/workflows/build.yml
This PR completes the work to move ITW 1.8.x builds onto GH Actions.
> ITW 1.8.x add Portable builds

- core/src/main/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesChecker.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesCheckerTest.java
> Do not check permissions for JNLP files without jars

- common/src/main/java/net/adoptopenjdk/icedteaweb/lockingfile/LockableFile.java
this has the effect that a read only file cannot be locked.
This seams reasonable as currently a read only file may throw an exception when a lock file is created for it.
This should fix https://github.com/karakun/OpenWebStart/issues/404
> only create lock file if the file is not read only

- .github/workflows/build.yml
- Makefile.am
- acinclude.m4
- configure.ac
Sparked from a recent conversation with @hendrikebbers. I have done some very basic testing using a jenkins slave jnlp file and it seems to launch it fine.
Follow up steps:
1. Generate an installer for ITW macOS (I can work on this in a follow up PR)
> initial macOS port

- core/src/main/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesChecker.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesCheckerTest.java
Fixes #265 (without side effects this time, I hope)
> fix: launching from local JNLP file triggers a warning dialog

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/DefaultControlPanelStyle.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/AccessWarningPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/AppletWarningPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/CertWarningPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/MissingALACAttributePanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/MissingPermissionsAttributePanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/apptrustwarningpanel/AppTrustWarningPanel.java
Fixes #753
Sorry, no unit tests as I don't see how this can be easily tested
> fix text color in security dialogs & control panel

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/DefaultControlPanelStyle.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/AccessWarningPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/AppletWarningPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/CertWarningPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/MissingALACAttributePanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/MissingPermissionsAttributePanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/apptrustwarningpanel/AppTrustWarningPanel.java
as proposed in #754 remove background color in security dialogs & control panel to improve text colors when running dark mode
> Improve text colors when running dark mode

- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages.properties
- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages_de.properties
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/DebuggingPanel.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/config/ConfigurationConstants.java
- core/src/main/java/net/sourceforge/jnlp/config/Defaults.java
Add the possibility to log the JNLP file content
> Log jnlp content

- .github/workflows/build.yml
- netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
Task #826 - IcedTeaWeb + Tomcat Cause "Unexpected End of ZLIB Input Stream" While Caching
> fix "Unexpected End of ZLIB Input Stream"

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/browser/HtmlBrowserPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/cache/CacheImpl.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/cache/CacheIndexEntry.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/cache/CacheKey.java
- core/src/main/java/net/sourceforge/jnlp/Launcher.java
- core/src/main/java/net/sourceforge/jnlp/runtime/classloader/JNLPClassLoader.java
- core/src/main/java/net/sourceforge/jnlp/runtime/classloader/LocateJnlpClassLoader.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/resources/ResourceTrackerTest.java
@sclassen this branch has been tested hence can be merged.
> Improve cache key

- pom.xml
Jcenter was shutdown 2 years ago.
> Removed jcenter
