- netx/net/sourceforge/jnlp/runtime/JNLPPolicy.java
see:  https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3720
> Jars of the jre itself are not recognized as such under windows

- Makefile.am
Currently the IcedTea-Web Windows installer can only be
built using an Admin account. By disabling the verification
it can be built by any user.
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>
> Allow installer to be built on AdoptOpenJDK infra

- netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
see: https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3715
> Packed resources are unnecessarily cached after unpacking

- netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
see: https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3714
> Packed resources are stored in cache with double file extension

- README
- netx/net/sourceforge/jnlp/controlpanel/JVMPanel.java
- rust-launcher/src/property.rs
- rust-launcher/src/property_from_file.rs
- rust-launcher/src/property_from_files_resolver.rs
- Check under windows against java.exe, instead of java, both in rust-launcher and in itweb-settings
- Unmasking the colon at properties in the rust launcher
https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3711
> Task #3711 - jre of the properties file does not work under windows

- Makefile.am
- acinclude.m4
- win-installer/installer.json.in
- change from java.bat to java.exe
- use HKLM\Software\Classes instead of HKCR, as entries are otherwise
made in HKCU\Software\Classes and then not apply to all users
- register jnlp-file and jnlps-protocol
> Adjustments to the msi-installer:

- Makefile.am
While making script for head, I had noticed there is hardcoded itw-installer.msi instead of using correct distname, which contains name and version
> Renamed msi to have versioned name

- core/src/test/java/net/sourceforge/jnlp/util/UrlUtilsTest.java
Hi,
The `UrlUtilsTest.testDecodeUrlAsFile()` test fails on Windows with the following error:
Running net.sourceforge.jnlp.util.UrlUtilsTest
Tests run: 24, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.479 sec <<< FAILURE!
testDecodeUrlAsFile(net.sourceforge.jnlp.util.UrlUtilsTest)  Time elapsed: 0.023 sec  <<< FAILURE!
java.lang.AssertionError: expected:<\simple> but was:<C:\simple>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at net.sourceforge.jnlp.util.UrlUtilsTest.testDecodeUrlAsFile(UrlUtilsTest.java:141)
I suggest comparing the decoded URL with the absolute file expected instead.
> UrlUtilsTest.testDecodeUrlAsFile() fails on Windows

- core/src/test/java/net/sourceforge/jnlp/TinyHttpdImplTest.java
Hi,
The `TinyHttpdImplTest.urlToFilePathTest()` test doesn't work on Windows because it checks unix style separators in the file paths. Here is a fix that will work everywhere.
> TinyHttpdImplTest.urlToFilePathTest() fails on Windows

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
There is no space between the console buttons:
This PR adds a 10px margin between them:
The layout of this window could be further improved (better alignment, margin consistency) but this is a first step. Is there any objection to use an advanced layout like [MigLayout](http://www.miglayout.com)? That would significantly simplify the code.
> Console buttons spacing

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
The console window can display more than one output, and it can also display no output at all, which doesn't seem very useful. I suggest forcing at least one output.
> Display at least one output in the console window

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyFileModel.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyFileModelTest.java
The `openAndParsePolicyFile()` method in `PolicyFileModel` acquires a FileLock on the policy file before parsing it. It doesn't seem to work on Windows with Java 8u191, several tests fail with the following error:
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:255)
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
at java.io.InputStreamReader.read(InputStreamReader.java:184)
at java.io.BufferedReader.fill(BufferedReader.java:161)
at java.io.BufferedReader.read(BufferedReader.java:182)
at …
> PolicyFileModel fails to parse the locked policy files on Windows

- launchers/build.sh
- launchers/configure.sh
- launchers/pom.xml
- launchers/rust-launcher/src/hardcoded_paths.rs
- launchers/rust-launcher/src/jars_helper.rs
- launchers/rust-launcher/src/main.rs
- launchers/rust-launcher/src/property_from_file.rs
- launchers/rust-launcher/src/utils.rs
- launchers/shell-launcher/launchers.sh.in
Hi!
this is adaptng launchers to now build. By default, they are nto build. You must use profile launchers to get them. Both shell and native ones are processed.  BOTH buuilt style was dropped, libs were narrowed.
The major usage would be:
MSLINKS_SRC=/home/blah/.m2/repository/com/github/vatbub/mslinks/1.0.5/mslinks-1.0.5.jar ITW_LIBS=DISTRIBUTION JRE=/usr/lib/jvm/java-1.8.0-openjdk mvn clean install -Plaunchers
and
ITW_LIBS=BUNDLED JRE=/usr/lib/jvm/java-1.8.0-openjdk mvn clean install -Plaunchers
All jars locations can be overwritten via variables. I have not found a better way in maven-shell connection.
This is still build only, .bats are missing (for now) and images (and thus msi) will come later.
> Launchers from pom

- .gitignore
- launchers/build.sh
- launchers/configure.sh
- launchers/pom.xml
Rust and shell launchers now generate distributable images.
Added clean phase
The images have version inherited from main pom
launchers/build.log and cargo.lock added to .gitignore
> Default launchers images

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPRuntime.java
- core/src/main/java/net/sourceforge/jnlp/util/logging/OutputController.java
`OutputController.flush()` is called in the shutdown hook of the OutputController.
If flush() has not been called before the shutdown hook is executed then the code was trying to initialize the awt toolkit.
The windows implementation of the toolkit will try to register another shutdown hook.
This fails if the shutdown is already in progress. The failure is unfortunately not handled very clean by the toolkit. As a consequence a thread is left in a `wait(0)` where it will stay forever.
This change makes sure that if flush is called during shutdown and the SwingUtils are not initialized then they will not be initialized.
> fix problems with shutdown hock of OutputController

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/AppletPermissionLevel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/ApplicationPermissionLevel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDesc.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
- core/src/main/java/net/sourceforge/jnlp/runtime/ManifestAttributesChecker.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDescTest.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/testing/mock/DummyJNLPFile.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/testing/mock/DummyJNLPFileWithJar.java
- core/src/test/java/net/sourceforge/jnlp/JNLPFileTest.java
- core/src/test/java/net/sourceforge/jnlp/PluginBridgeTest.java
- core/src/test/java/net/sourceforge/jnlp/runtime/CodeBaseClassLoaderTest.java
- core/src/test/java/net/sourceforge/jnlp/runtime/JNLPFileTest.java
- split RequestedPermissionLevel by AppletPermissionLevel and ApplicationPermissionLevel to better reflect JSR spec and entangle applet/html from application/jnlp logic
- improved documentation
> refactored SecurityDesc

- core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
- core/src/test/java/net/sourceforge/jnlp/PluginBridgeTest.java
The main change is to synchronize on `lruHandler` before calling `lruHandler.lock()`.
Otherwise sometimes a deadlock occurs where one thread holds the monitor on `lruHandler` and another thread holds the lock.
> fix dead lock between synchronize and lock on LRU Cache

- common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages_de.properties
- German translation for PUntrustedNative has the opposite meaning of the English text 
- fixed and used a positive wording instead of two times negative
> fix translation bug that inverted the meaning

- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPPolicy.java
Attempting to use built in java security packages when running java web start applications results in permission denials.  These permission denials occur upon initialization of the packages for sun security such as mscapi and jgss.    Even though an application has been allowed to run with all permissions, these packages were being denied runtime and security permissions.   Output for these denials are shown below: 
Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying permission: ("java.security.SecurityPermission" "putProviderProperty.XMLDSig")
Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying …
> Forced recognition of system jars

- configure.ac
- rust-launcher/src/hardcoded_paths.rs
- rust-launcher/src/jars_helper.rs
- rust-launcher/src/log_helper.rs
- rust-launcher/src/main.rs
- rust-launcher/src/property_from_file.rs
- rust-launcher/src/utils.rs
If itw is built in EMBEDDED mode, then it search for jre/jdk "where it is placed" right after java_home.
It is done by simple .., ../..
The search for libraries is then done in same way as for BUNDLED mode
> Added embedded mode

- core/src/main/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesChecker.java
- core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/manifest/ManifestAttributesCheckerTest.java
- core/src/test/java/net/sourceforge/jnlp/runtime/DummySecurityDelegate.java
- core/src/test/java/net/sourceforge/jnlp/util/UrlUtilsTest.java
Closes #256
I have created class DummySecurityDelegate as it seems that neither Mockito nor Easymock is used and I didn't want to introduce dependencies. Will happily do if required.
> fix(ManifestAttributesChecker): jars must be relative to codebase

- launchers/shell-launcher/launchers.sh.in
Trying to run IcedTea-Web in MacOSX (El Capitan) fails due to space in path.
I was trying to install it under /Library/Application Support/icedtea-web-image.
With this patch I was able to run my webstart applications.
The general class of fix is that in shell always enclose in double quotes variable expansions like a="$b".
The patch fixes PORTABLE_ITW_HOME as it should.
The patch doesn't change BINARY_LOCATION (next line) when it should.
Basically BINARY_LOCATION shouldn't work but it does and so I left it unchanged.
The following attached small test demonstrates this behavior.
and here is its output if you don't feel performing the test yourself. The test is on linux but it has the same behavior in MacOSX (El Capitan)
[test.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3268316/te …
> BUGFix: handle spaces in path names

- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/testcase1/SystemPropertiesSetTest.java
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/testcase1/jnlps/SimpleJavaApplicationWithProperties.jnlp
- Extend SystemPropertiesSetTest integration test to add system property from command line using "-property"
- Improved naming
> Add system property from commandline test case

- common/src/main/java/net/adoptopenjdk/icedteaweb/commandline/CommandLineOptionsParser.java
- common/src/test/java/net/adoptopenjdk/icedteaweb/commandline/CommandLineOptionsParserTest.java
- core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
- core/src/test/java/net/sourceforge/jnlp/runtime/BootTest.java
- simplify fetching JNLP file location from command line argument
- be more tolerant for unknown extra arguments by ignoring them when fetching JNLP file location instead of throwing an InvalidArgumentException
> simplify fetching JNLP file location from command line argument

- core/src/main/java/net/sourceforge/jnlp/runtime/ApplicationInstance.java
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/testcase1/SystemPropertiesSetTest.java
This makes it possible for the started application to detect the execution context.
Based on the presence of the system property, multi-deployment applications can adapt to the WebStart running context, and test frameworks can use special optimizations for WebStart runs.
> Always add system property "deployment.javaws"="IcedTea-Web"

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/ShortcutDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDescTest.java
- core/src/test/java/net/sourceforge/jnlp/ParserBasicTest.java
for parsing completeness according to JSR-56 and as preparation to be used to improve WindowsDesktopEntry shortcut handling (currently mostly throws UnsupportedOperationException)
> implement parsing of the shortcut install attribute

- core/src/main/java/net/sourceforge/jnlp/security/HttpsCertVerifier.java
The comma only has to be removed if derValue is null. But if derValue is null we have already thrown an NPE through derValue.getAsString(). Thus, the comma never has to be removed.
> small fix in getNamesForCert(X509Certificate c)

- core/src/main/java/net/sourceforge/jnlp/tools/JarCertVerifier.java
If you start an application. with several JARs and only 1 is corrupt you currently do not see any info about the file. This PR adds the name off the JAR to the error message
> Add the jar file name to exception message

- core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
- core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
- core/src/test/java/net/sourceforge/jnlp/cache/CacheUtilTest.java
AssertionError in CacheUtilTest:
tesPathUpNoGoBasic
tesPathUpNoGoBasic2
tesPathUpNoGoBasicEvil
tesPathUpNoGoBasicEvil2
tesPathUpNoGoBasicEvilest
tesPathUpNoGoBasicLong
testNameGotHashedToo
testQueryGotHAshedToo
IOException in JNLPClassLoaderTest:
testRelativePathInNestedJars
testRelativePathInUrl
> Fix for the following failed test on Windows

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDesc.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDescTest.java
- integration/pom.xml
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/reproducers/appletDescMainClassWithClass/AppletDescMainClassWithClassTest1.java
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/reproducers/appletDescMainClassWithClass/AppletDescMainClassWithClassTest2.java
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/reproducers/appletDescMainClassWithClass/applications/AppletDescMainClassWithClass.java
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/reproducers/appletDescMainClassWithClass/jnlps/AppletDescMainClassWithClass1.jnlp
- integration/src/test/java/net/adoptopenjdk/icedteaweb/integration/reproducers/appletDescMainClassWithClass/jnlps/AppletDescMainClassWithClass2.jnlp
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/361
appelts can have class specified both pkg.myclass and pkg.myclass.class
There are several places in ITW where this can be applied
I had decided to go eith direct getter from AppletDesc for several reasons:
- it is applet-desc specific, and application-desc should not be crippeld by this
- in checkForMain is palce where .class is appended, that would need to be adjsuted
- checkEntryPoint is comparin main class against record in manifest.
-- classes in manifest are supposed to be suffix .class free. Although you can smuggle class.class into manifest, that is usually bringing you toubles.
-- eg. java -jar willnot load such main-class
- I can be wrong with the manifest usage
> AppletDesc now accept also class.class suffixed  entry point in its applet-desc xml element

- pom.xml
Disable generation of JavaDoc by default.
A specialized profile `javaDoc` has been added to allow generation of javaDoc if required
> no source-jar or javadoc-jar

- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPSecurityManager.java
1. extend JNLPSecurityManager from SecurityManager instead of AWTSecurityManager
2. remove method getAppContext() from JNLPSecurityManager
>  #437 Application cannot be started with JDK 13 - AWTSecurityManager was removed

- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/ControlPanel.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/AboutPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/CacheSettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/CertificatesSettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/ControlPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/DebugSettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/DesktopSettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/JvmSettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/NetworkSettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/PolicySettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/SecuritySettingsPanelProvider.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/panels/provider/UnsignedAppletsTrustingListPanelProvider.java
Based on this we can remove unused panels (like the JVM Panel) in OWS. The current implementation used the name that depends on the translation
> title property added to control panels

- core/src/main/java/net/sourceforge/jnlp/cache/CachedDaemonThreadPoolProvider.java
- core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
We've had some problems with downloads getting stuck when starting an application. Problem seemed to be that IcedTea-Web started too many connections in a short amount of time, up to 100 in our case. This seemed to cause the network or firewall to freak out a bit.
Limiting the amount of parallel downloads solved the problem for us. Three is an arbitrary number we just made up, but it seemed to solve the problem without increasing the total load time. We had to split initializing and running the download to fix the progress indicator from going crazy.
> Stuck downloadingresources

- launchers/configure.sh
The current command in configure.sh selects two jar files (the normal one and the shaded one) and provokes a strange error when trying to build launchers on Windows.
I assume we want the shaded jar and not the normal one.
> #313 - Fix Windows launchers build

- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/ResourceHandler.java
Fix issues with whitespaces in JNLP filename (like `myApp (1).jnlp`). Fixes https://github.com/karakun/OpenWebStart/issues/68
> Handle whitespace in JNLP filename correctly

- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/cache/LeastRecentlyUsedCache.java
fixes https://github.com/karakun/OpenWebStart/issues/70
> use PropertiesFile to save jnlpPath - this ensures correct encoding

- core/src/main/java/net/sourceforge/jnlp/runtime/CachedJarFileCallback.java
- core/src/test/java/net/sourceforge/jnlp/runtime/JNLPClassLoaderTest.java
- core/src/test/resources/net/sourceforge/jnlp/runtime/test.jnlp
The problem is reproducible with cache folders that contain spaces. After starting an application, the resources are downloaded to cache folder but attempt to load main class fails with java.lang.ClassNotFoundException.
The problem seems to be caused by inconsistent escaping/unescaping of values of the map - net.sourceforge.jnlp.runtime.CachedJarFileCallback.mapping (associates remote URL with local URL).  Adding values to this map occurs in CachedJarFileCallback.addMapping(remoteURL, localURL) that is called from JNLPClassLoader.activateJars() which performs escaping (localFile->URI->URL) replacing spaces with %20. The getter is in CachedJarFileCallback.retrieve(URL) - for local files, it creates JarFile using escaped value and fails with FileNotFoundException (and swallows it later).The …
> Fix cache folder with space use case

- launchers/build.sh
- launchers/rust-launcher/Cargo.toml
- launchers/rust-launcher/src/main.rs
This was my first Rust experience, so hopefully the code's at least mediocre :D
> Launcher catchup 4 - Native Debug in Rust

- core/src/main/java/net/adoptopenjdk/icedteaweb/userdecision/FileStoreEntries.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/userdecision/FileStoreEntry.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/userdecision/UserDecision.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/userdecision/UserDecisionsFileStore.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/userdecision/UserDecisionsFileStoreTest.java
The new JSON file has the following structure:
```
{
"version": "1",
"userDecisions": [
{
"domain": "http://localhost",
"jarNames": [
"eager.jar",
"lazy.jar",
"native.jar"
],
"decisions": {
"RUN_UNSIGNED_APPLICATION": "DENY",
"RUN_MISSING_ALAC_APPLICATION": "ALLOW",
"RUN_MISSING_PERMISSIONS_APPLICATION": "SANDBOX"
}
}
]
}
```
The advantage is that multiple decisions can be stored in the same entry.
> change file store impl to make json more compact

- core/src/main/java/net/adoptopenjdk/icedteaweb/classloader/ApplicationTrustValidatorImpl.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/classloader/JnlpApplicationClassLoader.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/classloader/PartsHandler.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/classloader/JnlpApplicationClassLoaderTest.java
- integration-tests/classloader-integration-tests/src/test/java/net/adoptopenjdk/icedteaweb/integration/classloader/BasicClassloaderIntegrationTests.java
A JNLP file may have more than one eager part.
All the jars from all eager parts must be validated together.
This change ensures the above. The old implementation validated each eager part by itself.
> Multiple eager parts

- core/src/main/java/net/sourceforge/jnlp/Launcher.java
- core/src/main/java/net/sourceforge/jnlp/runtime/AppContextFactory.java
- core/src/main/java/net/sourceforge/jnlp/runtime/classloader/DelegatingClassLoader.java
The EventQueue.class stores the classloader in a final field classLoader. The EventQueue itself is stored static inside SunToolkit.class. Even if the active EDT thread classloader is modified to a JNLP classloader, classloading will fail once an AWTAutoShutdown occurs. (No edt activity for 1 second). If any new activity starts, the EDT Thread is recreated and initialized with the classloader stored in field classLoader in EventQueue class. This was not the JNLP classloader anymore. The result are ClassNotFound Exceptions. As there does not seem to be a "nice solution" because of the EventQueue implementation details the current solution temporary sets a DelegatingClassLoader to the thread which will initialize the eventqueue. Once initialized the original classloader is restored to the …
> Fixed EDT Classloading issues after EDT shutdown.

- netx/net/sourceforge/jnlp/runtime/CachedJarFileCallback.java
- tests/netx/unit/net/sourceforge/jnlp/runtime/CachedJarFileCallbackTest.java
> fix: JARs downloaded with URI-escaped characters don't get loaded

- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/downloader/JarDiffUnpacker.java
fixes #465 
Currently a FileNotFoundException is thrown when trying to apply a jardiff if the tmp folder does not exist. This fix makes sure the folder gets created if it does not exist yet.
> fix: tmp dir must be created, if it does not exist yet

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDesc.java
- core/src/main/java/net/sourceforge/jnlp/Parser.java
- core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDescTest.java
- core/src/test/java/net/sourceforge/jnlp/ParserTest.java
Provide an attribute to be able to implement logic to use a 32 bit JVM on a 64 bit Windows machine
> Allow to specify require 32 bit JVM in JNLP file

- core/src/main/java/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
Currently the path to user's desktop folder is defined as 
```     
private String getDesktopLnkPath() {
return System.getenv("userprofile") + "/Desktop/" + getShortcutFileName();
}
```
This is not always true.
It seems to be more reliable to get desktop path from windows registry
```     
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Desktop
```
Current definition may be used as a fallback if registry read fails or is impossible for some reason.
This pull request will probably fix https://github.com/karakun/OpenWebStart/issues/243 issue.
> the path to user's desktop folder is read from windows registry

- .github/workflows/build.yml
Allows us to cut a release to GH directly from actions
> add steps to publish release to GH

- .github/workflows/build.yml
- ChangeLog
- NEWS
- configure.ac
Release for backport from https://github.com/AdoptOpenJDK/IcedTea-Web/issues/89
> 1.8.7 release

- AUTHORS
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/ClientCertSelectionPane.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/SecurityDialog.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/SecurityDialogMessage.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/SecurityDialogMessageHandler.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/SecurityDialogs.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/ViwableDialog.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/ResourceTracker.java
- core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
- core/src/main/java/net/sourceforge/jnlp/runtime/JNLPRuntime.java
- core/src/main/java/net/sourceforge/jnlp/runtime/MergedKeyManager.java
- core/src/main/java/net/sourceforge/jnlp/runtime/classloader/JNLPClassLoader.java
a. Better HTTPS with Client authentication :
- In order to avoid too many PIN/Password requests (HTTPS hanshakes), downloads first the initial jar (mono-thread) then all remaining ones (multi-thread)
- In case of initial jar download failure (Client Certificate Selection cancel, incorrect PIN/Password, ...), fail fast and do not try to download remaining jars
- No resource prefetch, otherwise deployment.cache.parallelDownloadCount is not enforced
b. New Security Dialog UI for Client Certificate Selection :
- Ability to display details on each certificate
- Shown in TaskBar
- Cancellable
- Selection using double-click, Enter key or OK button
- Internationalization
c. SmartCard support on Windows
- Introduction of a Merged Key Manager for user, system and browser key stores
- Client alias …
> Better HTTPS with Client Authentication & SmartCard support on Windows

- netx/net/sourceforge/jnlp/runtime/JNLPSecurityManager.java
See Issue #437 
This is a trivial backport for the branch 1.8 to make icetea-web work on OpenJDK 13 to 17, tested on 15, 16, 17 EA.
> Backport PR #438: AWTSecurityManager was removed

- core/src/main/java/net/sourceforge/jnlp/tools/JarCertVerifier.java
The signature block for ECDSA signatures has the extension ".EC",
add that as possible METAINF entry.
Otherwise the JAR is considered as unsigned, when ECDSA signatures are used.
Signed-off-by: Frank Behrens <frank@harz.behrens.de>
> Support signed JARs with ECDSA signatures.

- core/src/main/java/net/sourceforge/jnlp/runtime/classloader/DelegatingClassLoader.java
Implement findResources(...) to load the resources from the delegate classloader.
closes #834
> Implement findResources(...) to load the resources from the delegate classloader

- core/src/main/java/net/sourceforge/jnlp/Parser.java
Hi everyone,
i've updated the parser.Java in order for it to be able to read size attributes when declared as "size=AAxBB"
This is related to issue #867.
Thanks,
Leonardo
> Update Parser.java to be able to read icon size attribute as "size="AAxBB"

- netx/net/sourceforge/jnlp/runtime/ApplicationInstance.java
Hi,
This PR aims to fix the following open issue:  #691: properties from extension jnlp are not set.
It does so by recursively visiting JNLP files referenced as extensions in the resources section to prepare a list of properties to be set all at once during an application's initialization phase.
The main benefit this approach is its simplicity while guaranteeing that properties will be set before code in the application (including in extensions) is executed, as mandated by the JNLP specification (JCP 56).
It does have the side effect of requesting the parsing - and therefore the download before that - of all JNLP files in the hierarchy. I have not observed that to be an issue in practice (jars and other resources should not be downloaded if not marked as "eager"), but it is something to …
>  Fixed issue #691: properties from extension jnlp are not set.

- Makefile.am
- configure.ac
- netx/net/sourceforge/jnlp/runtime/JNLPSecurityManager.java
- netx/net/sourceforge/jnlp/security/package-info.java
- tests/test-extensions/net/sourceforge/jnlp/tools/CodeSignerCreator.java
With this backporting, the 1.8 branch can also be built with java 11, 12 and 13, but only if the java plugin is disabled. This will certainly help some Linux package maintainers who are currently patching themselves to establish java 11 as the default java version in their distribution.
> backport of #868

- core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ExtensionDesc.java
- core/src/main/java/net/adoptopenjdk/icedteaweb/resources/cache/CacheImpl.java
- core/src/main/java/net/sourceforge/jnlp/JNLPFileFactory.java
Try to fix extension file cache lookup in issue #932
> Fix extension file cache lookup

- core/src/main/java/net/adoptopenjdk/icedteaweb/jvm/JvmUtils.java
These were introduced in Java 8u191 (2018-10-16).
An important note on `MinRAMPercentage`: it is only used on ''small'' heap sizes (think <100M). It is primarily used for container applications.
The properties match the following requirements:
* No `"` or `%` character (the double values do not include `%`)
* Values include `.` (0x2E) and 0-9 (0x30-0x39); that is between `0x20` and `0x17E`
* The strings do not include `\`
While these properties were originally introduced for containers, they are also useful for desktop applications. Of specific note, `MaxRAMPercentage` is useful for applications that can have a _small_ amount of data in memory to a _large_ amount of data in memory.
Default values:
* InitialRAMPercentage: 1.5625
* MinRamPercentage: 50.0
* MaxRamPercentage: 25.0
> Add additional valid starting VM arguments

- core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
Enable java.net built-in support of HTTP cookies. HTTP cookies will be stored in-memory until the java process dies.
> Enable basic HTTP cookie support in Boot.java

- rust-launcher/src/main.rs
- shell-launcher/launchers.sh.in
The Java security manager is deprecated since Java 17 and disabled by default since at least Java 21 (and subject to removal in a future release). For the time being enabling the security manager (as a workaround) leads to a working IcedTea-Web using Java 21.
Inspired by https://salsa.debian.org/java-team/icedtea-web/-/blob/master/debian/patches/javaws_change_java_policy.diff
> Prepend -Djava.security.manager as workaround for Java 21 (1.8)
